### ISSUE TITLE
user setting rules

### ISSUE THREAD

**Issue by briancrink** [kelvien/vscode-hue#8]
I have three rooms setup: bedroom, guest, living room (in alpha order as shown in the Home.app).

upon initial testing, I observed three issues.
1. value strings (as shown in the readme) like "guest" are not functioning for neither "lights" nor "groups" 

2. group elements change indices
Initially, I found each group corresponded with these rooms:
group 0 -> all
group 1 -> guest
group 2 -> bedroom
group 3 -> living room
now the indices correspond to arbitrary rooms:
group 0 -> all
group 1 -> living room + guest
group 2 -> bedroom
group 3 -> living room
group 4 -> bedroom

3. setting multiple lights to varying colors worked initially then became problematic
```
"python": {
      "lights": ["1", "2"],
      "state": {
        "on": true,
        "bri": 254,
        "hue": [44000, 10000],
        "sat": 254
      }
    },
```

**Comment by kelvien** [comment]
@briancrink thank you for bringing this to my attention!
I can take a look at the first two points this weekend. And for the third point, do you mind elaborating what sort of problem you were experiencing?

**Comment by briancrink** [comment]
@kelvien awesome project! I saw your reddit post.

Working with two lights, I intended to set each light to a different color for languages with color schemes like Python and Clojure. So for Python, the hue of light "1" would be 44000 and light "2" would be 10000. Setting the python object like shown above worked. 

Then added a few languages that like c, cpp, ts, php (that have monochromatic color schemes) setting both lights "1" and "2" to only one hue. Switching back to a Python file changed both lights to only the hue of the first int value (44000)

```
    "php": {
      "lights": ["1", "2"],
      "state": {
        "on": true,
        "bri": 254,
        "hue": 47000,
        "sat": 240
      }
    },
    "python": {
      "lights": ["1", "2"],
      "state": {
        "on": true,
        "bri": 254,
        "hue": [44000, 10000],
        "sat": 254
      }
    },
```

**Comment by kelvien** [comment]
Thank you @briancrink 
A recent release was to fix several issues, including some that you have brought up:
- Group names are now supported in the "Ambient lights" rules
- The rules now support multiple lights/groups with different states, so this will allow you to have two lights to have different colors. Please see the README for more details
- Group elements' indices shouldn't be a problem anymore since we can specify the group's names instead of the IDs in the rules.

**Comment by briancrink** [comment]
@kelvien works beautifully
